### ISSUE TITLE
読み込み待ち削除のため、ScreenCapture.CaptureScreenshotAsTextureを使いたい

### ISSUE THREAD

**Issue by ttyyamada** [nir-takemi/UnityTweet#2]
現状、`CaptureScreen()`で一度persistentDataPath配下にキャプチャ画像を作成してから
同名ファイルを読み込んでいるが、
[ScreenCapture.CaptureScreenshotAsTexture](https://docs.unity3d.com/ja/2018.4/ScriptReference/ScreenCapture.CaptureScreenshotAsTexture.html)
を使うことでファイル書き込みやキャプチャー処理の待ち時間の処理が省略可能です
こんな感じに処理をかけると思います

```
var tex = ScreenCapture.CaptureScreenshotAsTexture();

// imgurへアップロード
string UploadedURL = "";

UnityWebRequest www;

WWWForm wwwForm = new WWWForm();
wwwForm.AddField("image", Convert.ToBase64String(tex.EncodeToJPG()));
wwwForm.AddField("type", "base64");

www = UnityWebRequest.Post("https://api.imgur.com/3/image.xml", wwwForm);
```

[処理の参考URL全容はこちらです](https://github.com/ttyyamada/TweetWithScreenShotInWebGL/blob/master/Assets/TweetWithScreenShot/Scripts/TweetManager.cs)

ご一考いただけますと幸いです

**Comment by nir-takemi** [comment]
このようなやり方があるのですね……！
ありがとうございますmm
試させていただきますmm

**Comment by nir-takemi** [comment]
@ttyyamada 
だいぶ時間が経ってしまいましたが、v1.1.2でこちら対応させていただきました！
情報いただきありがとうございましたmm
